apiVersion: v1
kind: Pod
metadata:
  name: http-pod
spec:
  containers:
    - name: http-server
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: MONGODB_HOST
          value: mongodb-test
        - name: MONGODB_PORT
          value: "27017"
  volumes:
    - name: /mnt/data
      emptyDir: {}
